
import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQSection = () => {
  const faqs = [
    {
      question: "What is the StageMaster AI Suite?",
      answer: "The StageMaster AI Suite is a collection of specialized AI tools designed for theater production professionals. It includes tools for set design, costume creation, choreography, and lighting optimization, all powered by advanced AI technology to streamline your creative process."
    },
    {
      question: "Do I need to install any software to use these tools?",
      answer: "No, all StageMaster AI tools are web-based and run through ChatGPT's platform. You only need an internet connection and a ChatGPT Plus subscription to access the full functionality of these specialized AI assistants."
    },
    {
      question: "Can I use the designs created by these tools in commercial productions?",
      answer: "Yes, the output generated by StageMaster AI tools can be used in both commercial and non-commercial productions. However, we recommend reviewing the specific terms of service for each tool and OpenAI's usage policies for complete details on commercial use."
    },
    {
      question: "How accurate are the set designs and measurements?",
      answer: "TheaterSetDesignGPT creates reasonably accurate stage blueprints based on the information you provide. While the designs are professionally conceived, we recommend having a professional stage designer or engineer review the plans before construction, especially for complex or safety-critical elements."
    },
    {
      question: "Can I request specific historical periods for costume designs?",
      answer: "Absolutely! CostumeDesignGPT can create designs from virtually any historical period or imaginative setting. Simply specify the era, cultural influences, or reference images when making your request, and the AI will tailor its designs accordingly."
    },
    {
      question: "Do the choreography routines account for dancers of different skill levels?",
      answer: "Yes, ChoreographyGPT can create routines for beginners, intermediate, and advanced performers. Be sure to specify the skill level of your performers when making your request, and the AI will adjust the complexity of movements accordingly."
    },
    {
      question: "Can StageLightingGPT work with my specific lighting equipment?",
      answer: "StageLightingGPT can create lighting plans compatible with most standard theater lighting equipment. For best results, provide details about your available fixtures, control systems, and stage configuration when making your request."
    },
    {
      question: "Is PlaywriterGPT included in the StageMaster AI Suite?",
      answer: "Yes, PlaywriterGPT is the newest addition to our StageMaster AI Suite. It specializes in creating original play scripts and can be accessed separately through its dedicated link."
    }
  ];

  return (
    <section id="faq" className="py-20 relative">
      <div className="container px-4 mx-auto">
        <div className="text-center mb-12">
          <span className="px-3 py-1 text-xs font-medium rounded-full bg-white/10 text-white backdrop-blur-sm mb-4 inline-block">
            Questions & Answers
          </span>
          <h2 className="headline text-3xl md:text-4xl mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-white/70 max-w-2xl mx-auto">
            Find answers to common questions about the StageMaster AI Suite and how it can enhance your theatrical productions.
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem 
                key={index} 
                value={`item-${index}`}
                className="glass-card border-none"
              >
                <AccordionTrigger className="text-left px-6 py-4 text-white hover:text-stage-gold font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 text-white/70">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
